# Generated by Django 5.2.17 on 2026-09-16 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ticker",
            name="exchange",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="ticker",
            name="sector",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="PriceBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.DecimalField(decimal_places=4, max_digits=12)),
                ("high", models.DecimalField(decimal_places=4, max_digits=12)),
                ("low", models.DecimalField(decimal_places=4, max_digits=12)),
                ("close", models.DecimalField(decimal_places=4, max_digits=12)),
                ("volume", models.BigIntegerField()),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_bars",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticker", "date"),
                        name="unique_price_bar_per_ticker_date",
                    )
                ],
            },
        ),
    ]
