"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import dj_database_url
from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="django-insecure-changeme-in-env")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=Csv())

# Render inyecta RENDER_EXTERNAL_HOSTNAME automáticamente en cada servicio
# (ej. "trading-scoring-abcd.onrender.com"). Lo sumamos a lo que venga de
# ALLOWED_HOSTS en vez de reemplazarlo, para no perder localhost/127.0.0.1
# en dev ni cualquier host extra seteado a mano.
RENDER_EXTERNAL_HOSTNAME = config("RENDER_EXTERNAL_HOSTNAME", default="")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "market_data",
    "scoring",
    "backtesting",
    "agent",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASE_URL siempre viene de una variable de entorno, nunca hardcodeada
# (ver ../CLAUDE.md). Neon Postgres en todos los entornos, incluyendo dev local.
# DATABASE_SSL_REQUIRE se desactiva solo en CI, donde el servicio de Postgres
# de GitHub Actions no expone SSL (Neon en dev/prod sí lo exige siempre).

# Validación explícita antes de dj_database_url.parse(): un DATABASE_URL vacío
# o mal formado (ej. un secret de GitHub Actions mal seteado) produce un
# ImproperlyConfigured legible en vez del traceback críptico de
# dj_database_url ("Scheme '://' is unknown").
DATABASE_URL_RAW = config("DATABASE_URL", default="")
if not DATABASE_URL_RAW or "://" not in DATABASE_URL_RAW or DATABASE_URL_RAW.startswith("://"):
    raise ImproperlyConfigured(
        "DATABASE_URL no está seteada o es inválida. Verificá el secret en el "
        "entorno de despliegue (no debe incluir el prefijo 'DATABASE_URL=' ni "
        "comillas -- solo la connection string, ej. postgresql://user:pass@host/db)."
    )

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL_RAW,
        conn_max_age=600,
        ssl_require=config("DATABASE_SSL_REQUIRE", default=True, cast=bool),
    )
}


# Gemini API (agente explicador con tool-calling real -- ver agent/services.py)
# SDK oficial: google-genai (`from google import genai`). google-generativeai
# (el paquete anterior) está deprecado, EOL 2025-11-30 -- confirmado en PyPI
# antes de agregar la dependencia, no asumido.

GEMINI_API_KEY = config("GEMINI_API_KEY", default="")
# 01-etl-data-pipeline usa gemini-3.8-flash por default, pero en pruebas
# reales contra este proyecto (2026-09-16) ese modelo devolvió 503
# UNAVAILABLE ("high demand") de forma persistente, mientras que
# gemini-2.5-flash directamente dejó de estar disponible para API keys
# nuevas (404, la propia API recomienda migrar) -- gemini-3.6-flash es el
# que la API sugirió y el que efectivamente respondió en la corrida real.
GEMINI_MODEL = config("GEMINI_MODEL", default="gemini-3.6-flash")


# Django REST Framework
# Throttling agresivo SOLO en GET /api/scores/<symbol>/explain/ (ver
# api/throttling.py::AgentExplainThrottle) -- ese endpoint corre
# explain_score de forma síncrona dentro del request-response, y cada
# llamada consume cupo real del free tier de Gemini. Un scraper o bot
# pegándole en producción puede agotar la cuota del día para todo el
# proyecto, así que el límite es deliberadamente bajo (5/hora por IP
# anónima) -- mucho más restrictivo que cualquier otro endpoint de esta
# API, que solo leen de la propia base o corren yfinance.
REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_RATES": {
        "agent_explain": "5/hour",
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# whitenoise sirve estáticos directo desde el proceso de gunicorn en Render
# (sin servicio/CDN aparte); STATIC_ROOT es donde collectstatic los junta en
# build time. Sin esto, el admin de Django carga sin CSS en producción.

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
